// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckCredentials():Promise<boolean>;

export function DownloadPDF(arg1:string,arg2:string):Promise<void>;

export function GetCacheDir():Promise<string>;

export function GetTree():Promise<main.Tree>;

export function SetCredentials(arg1:string,arg2:string):Promise<void>;
