// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCredentials() {
  return window['go']['main']['App']['CheckCredentials']();
}

export function DownloadPDF(arg1, arg2) {
  return window['go']['main']['App']['DownloadPDF'](arg1, arg2);
}

export function FetchPDF(arg1) {
  return window['go']['main']['App']['FetchPDF'](arg1);
}

export function GetCacheDir() {
  return window['go']['main']['App']['GetCacheDir']();
}

export function GetTree() {
  return window['go']['main']['App']['GetTree']();
}

export function SetCredentials(arg1, arg2) {
  return window['go']['main']['App']['SetCredentials'](arg1, arg2);
}
